title: Made by Zack
description: Resources and notes for KS3/KS4 Computer Science
logo: "assets/images/mbz_logo_large.png"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Optional: configure the navigation
nav:
  - title: Home
    url: /
  - title: KS3
    children:
      - title: Year 7
        url: /ks3/year7
      - title: Year 8
        url: /ks3/year8
      - title: Year 9
        url: /ks3/year8
  - title: GCSE
    children:
      - title: Computer Systems
        url: /gcse/comp_sys
      - title: Computational Thinking
        url: /gcse/comp_think
